# Sample workflow to perform terratest against a test AWS account
name: AWS Terratest workflow
on: workflow_dispatch

env:
  AWS_REGION : "eu-west-2"

permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
  TerraTest:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
        
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ASSUME_ROLE }}
          role-session-name: gh-action-role-session
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Dependencies
        working-directory: tests/vpc/deployment
        run:  go get -v -t -d && go mod tidy

      - name: Test
        working-directory: tests/vpc/deployment
        run: go test -v