---
name: Release
on: workflow_dispatch

jobs:
  release:
    name: release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create release and publish
        id: release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 17.4.2
          extra_plugins: |
            conventional-changelog-conventionalcommits@^4.5.0
            @semantic-release/git@^9.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
